Advance opration with Business example.

In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [19]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])
print("========== Sales Data ==========")
print("\n Sales data Shape:", sales_data.shape) 
print("\n For First three restaurants:\n", sales_data[:3])

========== Sales Data ==========

 Sales data Shape: (5, 5)

 For First three restaurants:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


## Total Seals PEr Year

In [ ]:
print(np.sum(sales_data, axis=0))
yearly_total = np.sum(sales_data[:,1:], axis=0)
print("\n Yearly Total Sales: \n", yearly_total)
total_sum = np.sum(yearly_total)
print("\n Total Sales: \n", total_sum)

# minimum sales per restaurant
min_sales = np.min(sales_data[:,1:], axis=1)
print("\n Minimum Sales per Restaurant: \n", min_sales)

# maximum sales per restaurant
max_sales = np.max(sales_data[:,1:], axis=1)
print("\n Maximum Sales per Restaurant: \n", max_sales)


## Average Sales per Restaruants
avg_sales = np.mean(sales_data[:,1:], axis=1)
print('\n Avg. Sales Per Restaurant: \n', avg_sales)


[     15  810000  945000 1085000 1240000]

 Yearly Total Sales: 
 [ 810000  945000 1085000 1240000]

 Total Sales: 
 4080000

 Minimum Sales per Restaurant: 
 [150000 120000 200000 180000 160000]

 Maximum Sales per Restaurant: 
 [250000 190000 300000 270000 230000]

 Avg. Sales Per Restaurant: 
 [200000. 152500. 247500. 225000. 195000.]


## Vector add and multiplication, dot , etc.

In [54]:
vector1 = np.array([1,2,3])
vector2 = np.array([1,2,3])
print("Addition = ", vector1 + vector2)
print("multiplication =", vector1 * vector2)
dot_product = np.dot(vector1, vector2)
print("Dot Product =", dot_product)

Addition =  [2 4 6]
multiplication = [1 4 9]
Dot Product = 14
