In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.random.rand(3,3)
array3 = np.zeros((4,4))

In [9]:
np.save('array1', array1)
np.save("array2", array2)
np.save("array3", array3)

In [13]:
loaded_array2 = np.load("array2.npy")
print(loaded_array2)

[[0.80182135 0.94594697 0.33887346]
 [0.45302137 0.37502983 0.21299201]
 [0.48087022 0.52512773 0.11340664]]
