Numpy Array Oprations 

In [143]:
import numpy as np

In [144]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print('Basic Slicing: ', arr[2:7])
print(' slicing with step:', arr[1:8:2])
print('neg. indexing:', arr[-5:-3])

Basic Slicing:  [3 4 5 6 7]
 slicing with step: [2 4 6 8]
neg. indexing: [6 7]


In [145]:
arr_2d = np.array([[1,3,2],
                   [4,6,5],
                   [6,9,7]])
print("Specific element:", arr_2d[1,2])
print("entire row: ", arr_2d[2])
print("entire column: ", arr_2d[ :, 1])

Specific element: 5
entire row:  [6 9 7]
entire column:  [3 6 9]


## Sorting

In [146]:
unsorted = np.array([1,2,4,5,7,90,5,3,5,8,3,2,2,3,5,8,9,9,0,0,98,76,43])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[5,1],
                            [2,3],
                            [4,3,]])
print(" sorted 2d array by column: \n", np.sort(arr_2d_unsorted, axis=0))

Sorted Array:  [ 0  0  1  2  2  2  3  3  3  4  5  5  5  5  7  8  8  9  9 43 76 90 98]
 sorted 2d array by column: 
 [[2 1]
 [4 3]
 [5 3]]


## Filter 

In [147]:
number = np.array( [0,1,2,3,4,5,6,7,8,9,10])
even_number = number[number % 2 ==0 ]
print("Even no.:\n", even_number)

Even no.:
 [ 0  2  4  6  8 10]


## Filter by Mask

In [148]:
mask = number > 5
print (" no. thta are greter then 5 : \n ", number[mask])

 no. thta are greter then 5 : 
  [ 6  7  8  9 10]


## Fancy indexing VS np.where()

In [149]:
indicate = [ 0,2,4]
print(number[indicate])

where_result = np.where(number > 5)
print(where_result)
print(' np where: \n', number[where_result])

[0 2 4]
(array([ 6,  7,  8,  9, 10]),)
 np where: 
 [ 6  7  8  9 10]


## Adding and Removing data

In [150]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
concatenate = np.concatenate((arr1,arr2))
print(' concatenated array: \n', concatenate)

 concatenated array: 
 [1 2 3 4 5 6]


# array compatibility 

In [151]:
a = np.array([1,2,3,8])
b = np.array([9,4,4,2])
c = np.array([5,6,4,7])

print("Compatibility Shape : ", a.shape == b.shape == c.shape)

Compatibility Shape :  True


In [152]:
orignal = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((orignal, new_row))
print( orignal)
print( new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((orignal, new_col))
print(" with new column: \n", with_new_col)

[[1 2]
 [3 4]]
[[5 6]]
 with new column: 
 [[1 2 7]
 [3 4 8]]


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
delete = np.delete(arr,2)
print( delete)

[1 2 4 5]
