#NUMPY

In [6]:
import numpy as np

In [7]:
arr_1D = np.array([1,2,3,4,5,])
print('arr_1D: ', arr_1D)
arr_2D = np.array([[1,2,3],[4,5,6]])
print('arr_2D: ', arr_2D)

arr_1D:  [1 2 3 4 5]
arr_2D:  [[1 2 3]
 [4 5 6]]


# diff. b/w list and array

In [8]:
py_list = [ 1,3,4,5]
print(' list is:', py_list * 2)

np_array = np.array([2,4,6])
print('np_array: ', np_array * 2)

 list is: [1, 3, 4, 5, 1, 3, 4, 5]
np_array:  [ 4  8 12]


In [9]:
import time
starts = time.time()
py_list = [i* 2 for i in range(1000000)]
print('Time taken by list comprehension: ', time.time() - starts)

starts = time.time()
np_array = np.arange(1000000) * 2
print('Time taken by NumPy array: ', time.time() - starts)

Time taken by list comprehension:  0.02217698097229004
Time taken by NumPy array:  0.0015587806701660156


In [61]:
zero = np.zeros((9,9))
print('zero: \n', zero)

one = np.ones((9,9))
print('one: \n', one)

full = np.full((3,3), 19)
print('full array: \n', full)

random = np.random.rand(3,3)
print('random array: \n', random)

sequence = np.arange(0, 11, 3)
print('sequence array: \n', sequence)

zero: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
one: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
full array: 
 [[19 19 19]
 [19 19 19]
 [19 19 19]]
random array: 
 [[0.02950379 0.55779249 0.10371877]
 [0.63748309 0.80799431 0.82575309]
 [0.43422395 0.74732091 0.82979878]]
sequence array: 
 [0 3 6 9]


In [34]:
vector = np.array([1,2,3])
print('vector: \n', vector)

matrics = np.array([[1,2,3],
                     [2,2,3]])
print('matrix: \n', matrics)

tensor = np.array([[[2,4,5],[1,3,5], [1,2,3]]])
print('tensor: \n', tensor)



vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [2 2 3]]
tensor: 
 [[[2 4 5]
  [1 3 5]
  [1 2 3]]]


In [35]:
arr= np.array([[1,2,3], [2,4,3]])
print('shape : ', arr.shape)
print('number of dimensions: ', arr.ndim)
print('data type: ', arr.dtype)
print('size: ', arr.size)
print('item size: ', arr.itemsize)


shape :  (2, 3)
number of dimensions:  2
data type:  int64
size:  6
item size:  8


## Array Reshaping

In [56]:
arr = np.arange(12)          #[ 0  1  2  3  4  5  6  7  8  9 10 11]
print('orignal; ', arr)

reshape = arr.reshape((3, 4))
print("\nReshape array: ", reshape)

flattened = reshape.flatten()
print("Flattened array: ", flattened)

#retern view, instead of copy.
raveled = reshape.ravel()
print("Raveled array: ", raveled)

# Transpose
tranpose = reshape.T
print("Transposed array: \n", tranpose)

orignal;  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshape array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
